### ISSUE TITLE
one_hot_lnc_sim_0.90.6.txt not found.

### ISSUE THREAD

**Issue by myseverus** [sheng-n/SSCLMD#1]
Traceback (most recent call last):   File "C:/Users/20825/Desktop/bioinformations/SSCLMD-main/code/main.py", line 4, in <module>     from data_preprocess import load_data   File "C:\Users\20825\Desktop\bioinformations\SSCLMD-main\code\data_preprocess.py", line 168, in <module>     load_data(args)   File "C:\Users\20825\Desktop\bioinformations\SSCLMD-main\code\data_preprocess.py", line 73, in load_data     l_l_t = np.loadtxt("../data/dataset1/one_hot_lnc_sim_" + str(a) + str(b) + ".txt")   File "C:\anaconda\envs\mdformer\lib\site-packages\numpy\lib\npyio.py", line 1356, in loadtxt     arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,   File "C:\anaconda\envs\mdformer\lib\site-packages\numpy\lib\npyio.py", line 975, in _read     fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)   File "C:\anaconda\envs\mdformer\lib\site-packages\numpy\lib\_datasource.py", line 193, in open     return ds.open(path, mode, encoding=encoding, newline=newline)   File "C:\anaconda\envs\mdformer\lib\site-packages\numpy\lib\_datasource.py", line 533, in open     raise FileNotFoundError(f"{path} not found.") FileNotFoundError: ../data/dataset1/one_hot_lnc_sim_0.90.6.txt not found.

Hi! author, I am intersted to your paper , good work! but  I run the mian.py ,the code has't a  data, one_hot_lnc_sim_0.90.6.txt not found.
Can you give me the whole dataset? thank!

**Comment by sheng-n** [comment]
you should download data and run data_preparation.py and calculating_similarity.py to obtain all similarity file

**Comment by myseverus** [comment]
> 您应该下载数据并运行 data_preparation.py 和 calculating_similarity.py 以获取所有相似性文件

ok! I run the two procedure and generate the one_hot_lnc_sim_0.90.6.txt,but there are still some files missing
I run the mian.py respectly,the error appear 
FileNotFoundError: ../data/dataset1/lnc_att_graph.txt not found.

I hope you can provide all the data. Thank you

**Comment by sheng-n** [comment]
Your file path is wrong, it should be dataset1/lnc_att_graph.txt

**Comment by sheng-n** [comment]
Your file path should be adjusted to the appropriate location

**Comment by myseverus** [comment]
> Your file path should be adjusted to the appropriate location
nono! the file path is true! the picture are the all data file.
![image](https://github.com/user-attachments/assets/94722912-92fd-48e0-8de4-e87baa5507d9)
![image](https://github.com/user-attachments/assets/e398dbab-5d25-4b16-ac42-099273d0b6da)

**Comment by myseverus** [comment]
Could you please provide me with all the data? Thank you. Here is my email 3485407168@qq.com

**Comment by sheng-n** [comment]
![image](https://github.com/user-attachments/assets/1c951db3-526e-409f-b27a-e71239af3060)
You also need to run data_preparation.py to obtain lnc/mi/dis_att_graph.txt

**Comment by myseverus** [comment]
> ![image](https://private-user-images.githubusercontent.com/95516781/374383019-1c951db3-526e-409f-b27a-e71239af3060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzQ4MjMsIm5iZiI6MTcyODM3NDUyMywicGF0aCI6Ii85NTUxNjc4MS8zNzQzODMwMTktMWM5NTFkYjMtNTI2ZS00MDlmLWIyN2EtZTcxMjM5YWYzMDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA4MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MjJlOWRmN2IzNDBjY2YyZjU0MzUwYzUzMGUzYmE4NjdmZjcyZDE2ZDFiYzI1YjgwZWFkYzlhZDFkZGU2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eVELd95P1FSwtwVds7JU_EHF4ECa3lzMaYhWhB0KCzk) You also need to run data_preparation.py to obtain lnc/mi/dis_att_graph.txt

Thank you for your answer! but i have no these files lncRNA_mer_feature.txt、miRNA_mer_feature.txt、dis_sem_sim.txt

**Comment by sheng-n** [comment]
![image](https://github.com/user-attachments/assets/8d698c0e-3607-489f-a19c-6ba47c030f0b)
(1) Run lncRNA_mer/miRNA_mer() in '__main__': in data_preparation.py to obtain lncRNA_mer_feature.txt、miRNA_mer_feature.txt
(2) The dis_sem_sim.txt  file has been provided in data (dataset1/dataset2)

**Comment by myseverus** [comment]
> ![image](https://private-user-images.githubusercontent.com/95516781/374470138-8d698c0e-3607-489f-a19c-6ba47c030f0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODQ2NjMsIm5iZiI6MTcyODM4NDM2MywicGF0aCI6Ii85NTUxNjc4MS8zNzQ0NzAxMzgtOGQ2OThjMGUtMzYwNy00ODlmLWExOWMtNmJhNDdjMDMwZjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEwNDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYzc5ZDEwYWQ1Njg4Nzc5NTlmMjczYTVlMDM3ZmZjZTc5ZGYwY2Q2ZDNkYzdhODdjMjdjYTRiYzYxMjgzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H3y41e9dRkWwPoGBS1eypjGpXuKpbjHflsmY9jilxjs) (1) Run lncRNA_mer/miRNA_mer() in '**main**': in data_preparation.py to obtain lncRNA_mer_feature.txt、miRNA_mer_feature.txt (2) The dis_sem_sim.txt file has been provided in data (dataset1/dataset2)

thank you! I haved  solved  the problem.
